return {
  named: {
    "AElig": "Æ",
    "AElig;": "Æ",
    "AMP": "&",
    "AMP;": "&",
    "Aacute": "Á",
    "Aacute;": "Á",
    "Acirc": "Â",
    "Acirc;": "Â",
    "Agrave": "À",
    "Agrave;": "À",
    "Alpha;": "Α",
    "Aring": "Å",
    "Aring;": "Å",
    "Atilde": "Ã",
    "Atilde;": "Ã",
    "Auml": "Ä",
    "Auml;": "Ä",
    "Beta;": "Β",
    "COPY": "©",
    "COPY;": "©",
    "Ccedil": "Ç",
    "Ccedil;": "Ç",
    "Chi;": "Χ",
    "Dagger;": "‡",
    "Delta;": "Δ",
    "ETH": "Ð",
    "ETH;": "Ð",
    "Eacute": "É",
    "Eacute;": "É",
    "Ecirc": "Ê",
    "Ecirc;": "Ê",
    "Egrave": "È",
    "Egrave;": "È",
    "Epsilon;": "Ε",
    "Eta;": "Η",
    "Euml": "Ë",
    "Euml;": "Ë",
    "GT": ">",
    "GT;": ">",
    "Gamma;": "Γ",
    "Iacute": "Í",
    "Iacute;": "Í",
    "Icirc": "Î",
    "Icirc;": "Î",
    "Igrave": "Ì",
    "Igrave;": "Ì",
    "Iota;": "Ι",
    "Iuml": "Ï",
    "Iuml;": "Ï",
    "Kappa;": "Κ",
    "LT": "<",
    "LT;": "<",
    "Lambda;": "Λ",
    "Mu;": "Μ",
    "Ntilde": "Ñ",
    "Ntilde;": "Ñ",
    "Nu;": "Ν",
    "OElig;": "Œ",
    "Oacute": "Ó",
    "Oacute;": "Ó",
    "Ocirc": "Ô",
    "Ocirc;": "Ô",
    "Ograve": "Ò",
    "Ograve;": "Ò",
    "Omega;": "Ω",
    "Omicron;": "Ο",
    "Oslash": "Ø",
    "Oslash;": "Ø",
    "Otilde": "Õ",
    "Otilde;": "Õ",
    "Ouml": "Ö",
    "Ouml;": "Ö",
    "Phi;": "Φ",
    "Pi;": "Π",
    "Prime;": "″",
    "Psi;": "Ψ",
    "QUOT": "\"",
    "QUOT;": "\"",
    "REG": "®",
    "REG;": "®",
    "Rho;": "Ρ",
    "Scaron;": "Š",
    "Sigma;": "Σ",
    "THORN": "Þ",
    "THORN;": "Þ",
    "TRADE;": "™",
    "Tau;": "Τ",
    "Theta;": "Θ",
    "Uacute": "Ú",
    "Uacute;": "Ú",
    "Ucirc": "Û",
    "Ucirc;": "Û",
    "Ugrave": "Ù",
    "Ugrave;": "Ù",
    "Upsilon;": "Υ",
    "Uuml": "Ü",
    "Uuml;": "Ü",
    "Xi;": "Ξ",
    "Yacute": "Ý",
    "Yacute;": "Ý",
    "Yuml;": "Ÿ",
    "Zeta;": "Ζ",
    "aacute": "á",
    "aacute;": "á",
    "acirc": "â",
    "acirc;": "â",
    "acute": "´",
    "acute;": "´",
    "aelig": "æ",
    "aelig;": "æ",
    "agrave": "à",
    "agrave;": "à",
    "alefsym;": "ℵ",
    "alpha;": "α",
    "amp": "&",
    "amp;": "&",
    "and;": "∧",
    "ang;": "∠",
    "apos;": "'",
    "aring": "å",
    "aring;": "å",
    "asymp;": "≈",
    "atilde": "ã",
    "atilde;": "ã",
    "auml": "ä",
    "auml;": "ä",
    "bdquo;": "„",
    "beta;": "β",
    "brvbar": "¦",
    "brvbar;": "¦",
    "bull;": "•",
    "cap;": "∩",
    "ccedil": "ç",
    "ccedil;": "ç",
    "cedil": "¸",
    "cedil;": "¸",
    "cent": "¢",
    "cent;": "¢",
    "chi;": "χ",
    "circ;": "ˆ",
    "clubs;": "♣",
    "cong;": "≅",
    "copy": "©",
    "copy;": "©",
    "crarr;": "↵",
    "cup;": "∪",
    "curren": "¤",
    "curren;": "¤",
    "dArr;": "⇓",
    "dagger;": "†",
    "darr;": "↓",
    "deg": "°",
    "deg;": "°",
    "delta;": "δ",
    "diams;": "♦",
    "divide": "÷",
    "divide;": "÷",
    "eacute": "é",
    "eacute;": "é",
    "ecirc": "ê",
    "ecirc;": "ê",
    "egrave": "è",
    "egrave;": "è",
    "empty;": "∅",
    "emsp;": " ",
    "ensp;": " ",
    "epsilon;": "ε",
    "equiv;": "≡",
    "eta;": "η",
    "eth": "ð",
    "eth;": "ð",
    "euml": "ë",
    "euml;": "ë",
    "euro;": "€",
    "exist;": "∃",
    "fnof;": "ƒ",
    "forall;": "∀",
    "frac12": "½",
    "frac12;": "½",
    "frac14": "¼",
    "frac14;": "¼",
    "frac34": "¾",
    "frac34;": "¾",
    "frasl;": "⁄",
    "gamma;": "γ",
    "ge;": "≥",
    "gt": ">",
    "gt;": ">",
    "hArr;": "⇔",
    "harr;": "↔",
    "hearts;": "♥",
    "hellip;": "…",
    "iacute": "í",
    "iacute;": "í",
    "icirc": "î",
    "icirc;": "î",
    "iexcl": "¡",
    "iexcl;": "¡",
    "igrave": "ì",
    "igrave;": "ì",
    "image;": "ℑ",
    "infin;": "∞",
    "int;": "∫",
    "iota;": "ι",
    "iquest": "¿",
    "iquest;": "¿",
    "isin;": "∈",
    "iuml": "ï",
    "iuml;": "ï",
    "kappa;": "κ",
    "lArr;": "⇐",
    "lambda;": "λ",
    "lang;": "⟨",
    "laquo": "«",
    "laquo;": "«",
    "larr;": "←",
    "lceil;": "⌈",
    "ldquo;": "“",
    "le;": "≤",
    "lfloor;": "⌊",
    "lowast;": "∗",
    "loz;": "◊",
    "lrm;": "‎",
    "lsaquo;": "‹",
    "lsquo;": "‘",
    "lt": "<",
    "lt;": "<",
    "macr": "¯",
    "macr;": "¯",
    "mdash;": "—",
    "micro": "µ",
    "micro;": "µ",
    "middot": "·",
    "middot;": "·",
    "minus;": "−",
    "mu;": "μ",
    "nabla;": "∇",
    "nbsp": " ",
    "nbsp;": " ",
    "ndash;": "–",
    "ne;": "≠",
    "ni;": "∋",
    "not": "¬",
    "not;": "¬",
    "notin;": "∉",
    "nsub;": "⊄",
    "ntilde": "ñ",
    "ntilde;": "ñ",
    "nu;": "ν",
    "oacute": "ó",
    "oacute;": "ó",
    "ocirc": "ô",
    "ocirc;": "ô",
    "oelig;": "œ",
    "ograve": "ò",
    "ograve;": "ò",
    "oline;": "‾",
    "omega;": "ω",
    "omicron;": "ο",
    "oplus;": "⊕",
    "or;": "∨",
    "ordf": "ª",
    "ordf;": "ª",
    "ordm": "º",
    "ordm;": "º",
    "oslash": "ø",
    "oslash;": "ø",
    "otilde": "õ",
    "otilde;": "õ",
    "otimes;": "⊗",
    "ouml": "ö",
    "ouml;": "ö",
    "para": "¶",
    "para;": "¶",
    "part;": "∂",
    "permil;": "‰",
    "perp;": "⊥",
    "phi;": "φ",
    "pi;": "π",
    "piv;": "ϖ",
    "plusmn": "±",
    "plusmn;": "±",
    "pound": "£",
    "pound;": "£",
    "prime;": "′",
    "prod;": "∏",
    "prop;": "∝",
    "psi;": "ψ",
    "quot": "\"",
    "quot;": "\"",
    "rArr;": "⇒",
    "radic;": "√",
    "rang;": "⟩",
    "raquo": "»",
    "raquo;": "»",
    "rarr;": "→",
    "rceil;": "⌉",
    "rdquo;": "”",
    "real;": "ℜ",
    "reg": "®",
    "reg;": "®",
    "rfloor;": "⌋",
    "rho;": "ρ",
    "rlm;": "‏",
    "rsaquo;": "›",
    "rsquo;": "’",
    "sbquo;": "‚",
    "scaron;": "š",
    "sdot;": "⋅",
    "sect": "§",
    "sect;": "§",
    "shy": "­",
    "shy;": "­",
    "sigma;": "σ",
    "sigmaf;": "ς",
    "sim;": "∼",
    "spades;": "♠",
    "sub;": "⊂",
    "sube;": "⊆",
    "sum;": "∑",
    "sup1": "¹",
    "sup1;": "¹",
    "sup2": "²",
    "sup2;": "²",
    "sup3": "³",
    "sup3;": "³",
    "sup;": "⊃",
    "supe;": "⊇",
    "szlig": "ß",
    "szlig;": "ß",
    "tau;": "τ",
    "there4;": "∴",
    "theta;": "θ",
    "thetasym;": "ϑ",
    "thinsp;": " ",
    "thorn": "þ",
    "thorn;": "þ",
    "tilde;": "˜",
    "times": "×",
    "times;": "×",
    "trade;": "™",
    "uArr;": "⇑",
    "uacute": "ú",
    "uacute;": "ú",
    "uarr;": "↑",
    "ucirc": "û",
    "ucirc;": "û",
    "ugrave": "ù",
    "ugrave;": "ù",
    "uml": "¨",
    "uml;": "¨",
    "upsih;": "ϒ",
    "upsilon;": "υ",
    "uuml": "ü",
    "uuml;": "ü",
    "weierp;": "℘",
    "xi;": "ξ",
    "yacute": "ý",
    "yacute;": "ý",
    "yen": "¥",
    "yen;": "¥",
    "yuml": "ÿ",
    "yuml;": "ÿ",
    "zeta;": "ζ",
    "zwj;": "‍",
    "zwnj;": "‌"
  },
  windows: [
    8364,
    65533,
    8218,
    402,
    8222,
    8230,
    8224,
    8225,
    710,
    8240,
    352,
    8249,
    338,
    65533,
    381,
    65533,
    65533,
    8216,
    8217,
    8220,
    8221,
    8226,
    8211,
    8212,
    732,
    8482,
    353,
    8250,
    339,
    65533,
    382,
    376
  ]
}
